version: '2'

networks:
  frontnet:
    name: frontnet
    driver: bridge

services:
    
  sms-front:
    networks:
      - frontnet
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
